name: Feedback
version: 0.0.1
author: TheDiamondYT
description: Let your players give feedback about your server.
api: [2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6]
main: TheDiamondYT\Feedback\Loader
permissions:
  feedback.give:
    default: true
    description: 'Give feedback about the server'
  feedback.read:
    default: op
    description: 'Read feedback about the server'
